### ISSUE TITLE
getting permission errors when starting container, any idea what's wrong?

### ISSUE THREAD

**Issue by virtuman** [golden-garage/meteor-dev#6]
Hello, trying to setup a project to run from docker container and getting some permissions error.. wondering if there's anything that i'm not doing correctly. Any help would be greatly appreciated.

Here's what I tried to do so far:

`[root@srv1 meteor]# alias app='docker run -it --rm --name=app -v $PWD:/app -p 3000:3000 golden/meteor-dev' `
`[root@srv1 meteor]# app --settings settings.json`
```
[[[[[ /app ]]]]]

=> Started proxy.
/home/app/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: EACCES: permission denied, mkdir '/app/.meteor/local'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.wrapper [as mkdir] (/tools/fs/files.js:1535:35)
    at Object.files.mkdir_p (/tools/fs/files.js:431:11)
    at Object.files.writeFileAtomically (/tools/fs/files.js:986:9)
    at ProjectContext._saveResolverResultCache (/tools/project-context.js:576:11)
    at /tools/project-context.js:551:14
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:486:20
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:141:3)
    at ProjectContext._resolveConstraints (/tools/project-context.js:485:13)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/runners/run-app.js:549:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:548:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

**Comment by golden-garage** [comment]
Hi Alexei,

Your steps look correct to me. I tested locally with a new pull of golden/meteor-dev, however I could not reproduce your error.

Have you checked the permissions of the $PWD directory - the directory where you are running the commands (meteor?). Meteor needs to be able to write to this directory.

The specific error is ‘cannot create meteor’s working directory - $PWD/.meteor/local’ - so, check that you can create a new directory at $PWD/.meteor/local.

Let me know if it is a permission problem on your side. If you still cannot get it working, I will do further testing.

Thanks,
Rick
