### ISSUE TITLE
i  install meteor in my singularity images ,and i run meteor  in my app directory 

### ISSUE THREAD

**Issue by supermanhuyu** [golden-garage/meteor-dev#7]
i  install meteor in my singularity images ,and i run meteor  in my app directory (/atlas/projects/ailab),and my home directory is /atlas/home/yhu/.
the fault is blow ....,i do not know what is wrong.

```
Singularity meteor.img:/atlas/projects/ailab> ls 
CHANGELOG.md  LICENSE  README.md  client  imports  node_modules  package.json  public  server
Singularity meteor.img:/atlas/projects/ailab> meteor 
/atlas/home/yhu/.meteor/packages/meteor-tool/.1.5.0.utbu0o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: EACCES: permission denied, open '/atlas/home/yhu/.meteor/packages/meteor-tool/.build857574..1.4.4_1.npmtlw++os.linux.x86_64+web.browser+web.cordova/.builder-tmp-file.733501'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.wrapper [as writeFile] (/tools/fs/files.js:1586:35)
    at atomicallyRewriteFile (/tools/isobuild/builder.js:710:9)
    at Builder.writeJson (/tools/isobuild/builder.js:298:5)
    at /tools/isobuild/isopack.js:1437:17
    at Array.forEach (native)
    at Function._.each._.forEach (/atlas/home/yhu/.meteor/packages/meteor-tool/.1.5.0.utbu0o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at [object Object].saveToPath (/tools/isobuild/isopack.js:1272:9)
    at [object Object]._.extend._saveIsopack (/tools/packaging/tropohouse.js:353:15)
    at /tools/packaging/tropohouse.js:526:16
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/packaging/tropohouse.js:515:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:600:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:597:20)
    at /tools/cli/main.js:462:30
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at /tools/cli/main.js:461:17
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at /tools/cli/main.js:459:33
    at [object Object]._.extend.withProgressDisplayVisible (/tools/console/console.js:639:14)
    at springboard (/tools/cli/main.js:458:11)
    at /tools/cli/main.js:1126:5
```

**Comment by supermanhuyu** [comment]
when  finished downloading meteor-tool ,apper this fault
